export interface ResourceMetrics {
  cpu: number;
  ram: number;
  storage: number;
  network: number;
  gpu: number;
  efficiency: number; // 0–100
}

export function total(m: ResourceMetrics): number {
  return m.cpu + m.ram + m.storage + m.network + m.gpu;
}

export interface Pod extends ResourceMetrics {
  id: string;
  name: string;
}

export interface Namespace extends ResourceMetrics {
  id: string;
  name: string;
  pods: Pod[];
}

export interface Cluster extends ResourceMetrics {
  id: string;
  name: string;
  namespaces: Namespace[];
}

export const clusters: Cluster[] = [
  {
    id: "cluster-a",
    name: "Cluster A",
    cpu: 2463,
    ram: 1368,
    storage: 246,
    network: 307,
    gpu: 821,
    efficiency: 10,
    namespaces: [
      {
        id: "ns-a1",
        name: "Namespace A",
        cpu: 1231,
        ram: 684,
        storage: 123,
        network: 153,
        gpu: 410,
        efficiency: 5,
        pods: [
          {
            id: "pod-a1a",
            name: "Pod A",
            cpu: 862,
            ram: 479,
            storage: 86,
            network: 107,
            gpu: 410,
            efficiency: 8,
          },
          {
            id: "pod-a1b",
            name: "Pod B",
            cpu: 246,
            ram: 136,
            storage: 24,
            network: 30,
            gpu: 0,
            efficiency: 40,
          },
          {
            id: "pod-a1c",
            name: "Pod C",
            cpu: 86,
            ram: 47,
            storage: 8,
            network: 10,
            gpu: 0,
            efficiency: 35,
          },
          {
            id: "pod-a1d",
            name: "Pod D",
            cpu: 37,
            ram: 22,
            storage: 5,
            network: 6,
            gpu: 0,
            efficiency: 70,
          },
        ],
      },
      {
        id: "ns-a2",
        name: "Namespace B",
        cpu: 739,
        ram: 410,
        storage: 73,
        network: 92,
        gpu: 246,
        efficiency: 20,
        pods: [
          {
            id: "pod-a2a",
            name: "Pod A",
            cpu: 450,
            ram: 260,
            storage: 45,
            network: 56,
            gpu: 246,
            efficiency: 12,
          },
          {
            id: "pod-a2b",
            name: "Pod B",
            cpu: 180,
            ram: 100,
            storage: 18,
            network: 22,
            gpu: 0,
            efficiency: 38,
          },
          {
            id: "pod-a2c",
            name: "Pod C",
            cpu: 109,
            ram: 50,
            storage: 10,
            network: 14,
            gpu: 0,
            efficiency: 55,
          },
        ],
      },
      {
        id: "ns-a3",
        name: "Namespace C",
        cpu: 369,
        ram: 205,
        storage: 36,
        network: 46,
        gpu: 123,
        efficiency: 50,
        pods: [
          {
            id: "pod-a3a",
            name: "Pod A",
            cpu: 200,
            ram: 110,
            storage: 20,
            network: 25,
            gpu: 123,
            efficiency: 45,
          },
          {
            id: "pod-a3b",
            name: "Pod B",
            cpu: 169,
            ram: 95,
            storage: 16,
            network: 21,
            gpu: 0,
            efficiency: 60,
          },
        ],
      },
      {
        id: "ns-a4",
        name: "Namespace D",
        cpu: 124,
        ram: 69,
        storage: 14,
        network: 16,
        gpu: 42,
        efficiency: 40,
        pods: [
          {
            id: "pod-a4a",
            name: "Pod A",
            cpu: 80,
            ram: 45,
            storage: 9,
            network: 10,
            gpu: 42,
            efficiency: 35,
          },
          {
            id: "pod-a4b",
            name: "Pod B",
            cpu: 44,
            ram: 24,
            storage: 5,
            network: 6,
            gpu: 0,
            efficiency: 50,
          },
        ],
      },
    ],
  },
  {
    id: "cluster-b",
    name: "Cluster B",
    cpu: 2127,
    ram: 1181,
    storage: 212,
    network: 265,
    gpu: 0,
    efficiency: 28,
    namespaces: [
      {
        id: "ns-b1",
        name: "Namespace A",
        cpu: 1050,
        ram: 580,
        storage: 104,
        network: 131,
        gpu: 0,
        efficiency: 22,
        pods: [
          {
            id: "pod-b1a",
            name: "Pod A",
            cpu: 600,
            ram: 330,
            storage: 60,
            network: 75,
            gpu: 0,
            efficiency: 18,
          },
          {
            id: "pod-b1b",
            name: "Pod B",
            cpu: 280,
            ram: 155,
            storage: 28,
            network: 35,
            gpu: 0,
            efficiency: 30,
          },
          {
            id: "pod-b1c",
            name: "Pod C",
            cpu: 170,
            ram: 95,
            storage: 16,
            network: 21,
            gpu: 0,
            efficiency: 45,
          },
        ],
      },
      {
        id: "ns-b2",
        name: "Namespace B",
        cpu: 680,
        ram: 378,
        storage: 68,
        network: 85,
        gpu: 0,
        efficiency: 35,
        pods: [
          {
            id: "pod-b2a",
            name: "Pod A",
            cpu: 400,
            ram: 220,
            storage: 40,
            network: 50,
            gpu: 0,
            efficiency: 30,
          },
          {
            id: "pod-b2b",
            name: "Pod B",
            cpu: 280,
            ram: 158,
            storage: 28,
            network: 35,
            gpu: 0,
            efficiency: 42,
          },
        ],
      },
      {
        id: "ns-b3",
        name: "Namespace C",
        cpu: 397,
        ram: 223,
        storage: 40,
        network: 49,
        gpu: 0,
        efficiency: 42,
        pods: [
          {
            id: "pod-b3a",
            name: "Pod A",
            cpu: 220,
            ram: 122,
            storage: 22,
            network: 27,
            gpu: 0,
            efficiency: 38,
          },
          {
            id: "pod-b3b",
            name: "Pod B",
            cpu: 177,
            ram: 101,
            storage: 18,
            network: 22,
            gpu: 0,
            efficiency: 48,
          },
        ],
      },
    ],
  },
  {
    id: "cluster-c",
    name: "Cluster C",
    cpu: 1702,
    ram: 945,
    storage: 170,
    network: 212,
    gpu: 567,
    efficiency: 15,
    namespaces: [
      {
        id: "ns-c1",
        name: "Namespace A",
        cpu: 850,
        ram: 470,
        storage: 85,
        network: 106,
        gpu: 283,
        efficiency: 10,
        pods: [
          {
            id: "pod-c1a",
            name: "Pod A",
            cpu: 500,
            ram: 277,
            storage: 50,
            network: 63,
            gpu: 283,
            efficiency: 8,
          },
          {
            id: "pod-c1b",
            name: "Pod B",
            cpu: 220,
            ram: 122,
            storage: 22,
            network: 27,
            gpu: 0,
            efficiency: 15,
          },
          {
            id: "pod-c1c",
            name: "Pod C",
            cpu: 130,
            ram: 71,
            storage: 13,
            network: 16,
            gpu: 0,
            efficiency: 25,
          },
        ],
      },
      {
        id: "ns-c2",
        name: "Namespace B",
        cpu: 510,
        ram: 283,
        storage: 51,
        network: 64,
        gpu: 174,
        efficiency: 22,
        pods: [
          {
            id: "pod-c2a",
            name: "Pod A",
            cpu: 300,
            ram: 167,
            storage: 30,
            network: 38,
            gpu: 174,
            efficiency: 18,
          },
          {
            id: "pod-c2b",
            name: "Pod B",
            cpu: 210,
            ram: 116,
            storage: 21,
            network: 26,
            gpu: 0,
            efficiency: 30,
          },
        ],
      },
      {
        id: "ns-c3",
        name: "Namespace C",
        cpu: 342,
        ram: 192,
        storage: 34,
        network: 42,
        gpu: 110,
        efficiency: 30,
        pods: [
          {
            id: "pod-c3a",
            name: "Pod A",
            cpu: 200,
            ram: 111,
            storage: 20,
            network: 25,
            gpu: 110,
            efficiency: 25,
          },
          {
            id: "pod-c3b",
            name: "Pod B",
            cpu: 142,
            ram: 81,
            storage: 14,
            network: 17,
            gpu: 0,
            efficiency: 38,
          },
        ],
      },
    ],
  },
  {
    id: "cluster-d",
    name: "Cluster D",
    cpu: 1057,
    ram: 587,
    storage: 105,
    network: 132,
    gpu: 0,
    efficiency: 43,
    namespaces: [
      {
        id: "ns-d1",
        name: "Namespace A",
        cpu: 520,
        ram: 289,
        storage: 52,
        network: 65,
        gpu: 0,
        efficiency: 38,
        pods: [
          {
            id: "pod-d1a",
            name: "Pod A",
            cpu: 300,
            ram: 167,
            storage: 30,
            network: 38,
            gpu: 0,
            efficiency: 35,
          },
          {
            id: "pod-d1b",
            name: "Pod B",
            cpu: 140,
            ram: 78,
            storage: 14,
            network: 17,
            gpu: 0,
            efficiency: 42,
          },
          {
            id: "pod-d1c",
            name: "Pod C",
            cpu: 80,
            ram: 44,
            storage: 8,
            network: 10,
            gpu: 0,
            efficiency: 55,
          },
        ],
      },
      {
        id: "ns-d2",
        name: "Namespace B",
        cpu: 310,
        ram: 172,
        storage: 31,
        network: 39,
        gpu: 0,
        efficiency: 50,
        pods: [
          {
            id: "pod-d2a",
            name: "Pod A",
            cpu: 180,
            ram: 100,
            storage: 18,
            network: 22,
            gpu: 0,
            efficiency: 45,
          },
          {
            id: "pod-d2b",
            name: "Pod B",
            cpu: 130,
            ram: 72,
            storage: 13,
            network: 17,
            gpu: 0,
            efficiency: 58,
          },
        ],
      },
      {
        id: "ns-d3",
        name: "Namespace C",
        cpu: 227,
        ram: 126,
        storage: 22,
        network: 28,
        gpu: 0,
        efficiency: 60,
        pods: [
          {
            id: "pod-d3a",
            name: "Pod A",
            cpu: 130,
            ram: 72,
            storage: 13,
            network: 16,
            gpu: 0,
            efficiency: 55,
          },
          {
            id: "pod-d3b",
            name: "Pod B",
            cpu: 97,
            ram: 54,
            storage: 9,
            network: 12,
            gpu: 0,
            efficiency: 68,
          },
        ],
      },
    ],
  },
];
